module.exports = {
  apps: [
    {
      name: 'edel-vote-bot',
      script: 'src/index.js',
      args: 'start',
      interpreter: 'node',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      merge_logs: true,
      restart_delay: 10000,
      max_restarts: 10,
      min_uptime: '30s',
    },
    {
      name: 'edel-session-refresh',
      script: 'scripts/auto-refresh.js',
      interpreter: 'node',
      cwd: './',
      instances: 1,
      autorestart: false,
      cron_restart: '0 */10 * * *',
      watch: false,
      max_memory_restart: '200M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/pm2-session-error.log',
      out_file: './logs/pm2-session-out.log',
      merge_logs: true,
    },
  ],
};
